"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 00:59:48.304161
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE purchase_order_number_seq START WITH 1001")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='supplier_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_suppliers_supplier_status')),
    sa.CheckConstraint('lead_time_days >= 0', name=op.f('ck_suppliers_lead_time_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WAREHOUSE_MANAGER', 'INVENTORY_MANAGER', 'PURCHASING_MANAGER', 'ANALYST', name='user_role', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'WAREHOUSE_MANAGER', 'INVENTORY_MANAGER', 'PURCHASING_MANAGER', 'ANALYST')", name=op.f('ck_users_user_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='warehouse_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_warehouses_warehouse_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_records_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', 'scope', name=op.f('pk_idempotency_records'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('FORECAST_ITEM', 'FORECAST_ALL', 'IMPORT_SALES', name='job_type', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='job_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')", name=op.f('ck_jobs_job_status')),
    sa.CheckConstraint("type IN ('FORECAST_ITEM', 'FORECAST_ALL', 'IMPORT_SALES')", name=op.f('ck_jobs_job_type')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('uq_jobs_active_dedupe_key', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_products_cost_non_negative')),
    sa.CheckConstraint('lead_time_days >= 0', name=op.f('ck_products_lead_time_non_negative')),
    sa.CheckConstraint('min_stock >= 0', name=op.f('ck_products_min_stock_non_negative')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_price_non_negative')),
    sa.CheckConstraint('reorder_point >= 0', name=op.f('ck_products_reorder_point_non_negative')),
    sa.CheckConstraint('safety_stock >= 0', name=op.f('ck_products_safety_stock_non_negative')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_products_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_supplier_id', 'products', ['supplier_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'CONFIRMED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='purchase_order_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('order_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'CONFIRMED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')", name=op.f('ck_purchase_orders_purchase_order_status')),
    sa.CheckConstraint('expected_delivery_date IS NULL OR expected_delivery_date >= order_date', name=op.f('ck_purchase_orders_expected_after_order')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_purchase_orders_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number'))
    )
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_purchase_orders_supplier_id', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index('ix_purchase_orders_warehouse_id', 'purchase_orders', ['warehouse_id'], unique=False)
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('history_start', sa.Date(), nullable=True),
    sa.Column('history_end', sa.Date(), nullable=True),
    sa.Column('history_days', sa.Integer(), nullable=False),
    sa.Column('total_predicted', sa.Float(), nullable=False),
    sa.Column('avg_daily_demand', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_forecast_runs_horizon_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_forecast_runs_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_forecast_runs_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs'))
    )
    op.create_index('ix_forecast_runs_item_generated', 'forecast_runs', ['product_id', 'warehouse_id', 'generated_at'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), sa.Computed('quantity_on_hand - reserved_quantity', persisted=True), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_inventory_items_on_hand_non_negative')),
    sa.CheckConstraint('reorder_point IS NULL OR reorder_point >= 0', name=op.f('ck_inventory_items_reorder_point_non_negative')),
    sa.CheckConstraint('reserved_quantity <= quantity_on_hand', name=op.f('ck_inventory_items_reserved_within_on_hand')),
    sa.CheckConstraint('reserved_quantity >= 0', name=op.f('ck_inventory_items_reserved_non_negative')),
    sa.CheckConstraint('safety_stock IS NULL OR safety_stock >= 0', name=op.f('ck_inventory_items_safety_stock_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_items_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_inventory_items_product_warehouse')
    )
    op.create_index('ix_inventory_items_warehouse_id', 'inventory_items', ['warehouse_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE_RECEIPT', 'SALE', 'ISSUE', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN', 'RETURN', 'RESERVATION', 'RESERVATION_RELEASE', name='transaction_type', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('on_hand_delta', sa.Integer(), nullable=False),
    sa.Column('reserved_delta', sa.Integer(), nullable=False),
    sa.Column('on_hand_after', sa.Integer(), nullable=False),
    sa.Column('reserved_after', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transfer_group', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('PURCHASE_RECEIPT', 'SALE', 'ISSUE', 'ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN', 'RETURN', 'RESERVATION', 'RESERVATION_RELEASE')", name=op.f('ck_inventory_transactions_transaction_type')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_transactions_quantity_positive')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_inventory_transactions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_transactions_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_transactions_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    op.create_index('ix_inventory_transactions_created_at', 'inventory_transactions', ['created_at'], unique=False)
    op.create_index('ix_inventory_transactions_product_wh_created', 'inventory_transactions', ['product_id', 'warehouse_id', 'created_at'], unique=False)
    op.create_index('ix_inventory_transactions_transfer_group', 'inventory_transactions', ['transfer_group'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity_ordered > 0', name=op.f('ck_purchase_order_lines_quantity_ordered_positive')),
    sa.CheckConstraint('quantity_received <= quantity_ordered', name=op.f('ck_purchase_order_lines_received_within_ordered')),
    sa.CheckConstraint('quantity_received >= 0', name=op.f('ck_purchase_order_lines_quantity_received_non_negative')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_purchase_order_lines_unit_cost_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines')),
    sa.UniqueConstraint('purchase_order_id', 'product_id', name='uq_po_lines_po_product')
    )
    op.create_index('ix_purchase_order_lines_product_id', 'purchase_order_lines', ['product_id'], unique=False)
    op.create_table('purchase_order_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('receipt_key', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_receipts_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_purchase_order_receipts_received_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_receipts')),
    sa.UniqueConstraint('purchase_order_id', 'receipt_key', name='uq_po_receipts_po_key')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sales_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_sales_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('order_reference', 'product_id', 'warehouse_id', name='uq_sales_order_product_warehouse')
    )
    op.create_index('ix_sales_product_wh_sold_at', 'sales', ['product_id', 'warehouse_id', 'sold_at'], unique=False)
    op.create_index('ix_sales_sold_at', 'sales', ['sold_at'], unique=False)
    op.create_table('forecast_points',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=False),
    sa.Column('lower', sa.Float(), nullable=False),
    sa.Column('upper', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], name=op.f('fk_forecast_points_run_id_forecast_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'forecast_date', name=op.f('pk_forecast_points'))
    )
    op.create_table('purchase_order_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_order_receipt_lines_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_receipt_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], name=op.f('fk_purchase_order_receipt_lines_purchase_order_line_id_purchase_order_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_order_receipts.id'], name=op.f('fk_purchase_order_receipt_lines_receipt_id_purchase_order_receipts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_receipt_lines'))
    )
    op.create_index(op.f('ix_purchase_order_receipt_lines_receipt_id'), 'purchase_order_receipt_lines', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_receipt_lines_receipt_id'), table_name='purchase_order_receipt_lines')
    op.drop_table('purchase_order_receipt_lines')
    op.drop_table('forecast_points')
    op.drop_index('ix_sales_sold_at', table_name='sales')
    op.drop_index('ix_sales_product_wh_sold_at', table_name='sales')
    op.drop_table('sales')
    op.drop_table('purchase_order_receipts')
    op.drop_index('ix_purchase_order_lines_product_id', table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index('ix_inventory_transactions_transfer_group', table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_product_wh_created', table_name='inventory_transactions')
    op.drop_index('ix_inventory_transactions_created_at', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('ix_inventory_items_warehouse_id', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_forecast_runs_item_generated', table_name='forecast_runs')
    op.drop_table('forecast_runs')
    op.drop_index('ix_purchase_orders_warehouse_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_supplier_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_products_supplier_id', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_table('products')
    op.drop_index('uq_jobs_active_dedupe_key', table_name='jobs', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('idempotency_records')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS purchase_order_number_seq")
